receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "nginx"
          static_configs:
            - targets: ["nginx-exporter:9113"]
        - job_name: "homeassistant"
          static_configs:
            - targets: ["192.168.1.30:8123"]
        - job_name: "otel-collector"
          static_configs:
            - targets: ["otel-collector:9464"]

processors:
  filter/otel_self:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - up
          - scrape_duration_seconds
          - scrape_samples_post_metric_relabeling
          - scrape_samples_scraped
          - scrape_series_added
          - target_scrape_pool_sync_total

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [filter/otel_self]
      exporters: [prometheus]
